name: EmployeeDB_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- main
pool:
  name: Default
variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildPlatform
  value: 'Any CPU'
- name: BuildConfiguration
  value: 'Release'

resources:
  repositories:
  - repository: self
    type: git
    ref: main
steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: VSBuild@1
    displayName: 'Build solution **\*.sln'
    inputs:
      solution: $(BuildParameters.solution)
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**\bin\$(BuildConfiguration)\**'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
